FROM ubuntu:bionic

RUN apt-get update \
    && apt-get -y install libc++1 pkg-config wget

RUN wget https://github.com/Kitware/CMake/releases/download/v3.17.2/cmake-3.17.2-Linux-x86_64.sh \
    -q -O /tmp/cmake-install.sh \
    && chmod u+x /tmp/cmake-install.sh \
    && mkdir /usr/bin/cmake \
    && /tmp/cmake-install.sh --skip-license --prefix=/usr/bin/cmake \
    && rm /tmp/cmake-install.sh

ENV PATH="/usr/bin/cmake/bin:${PATH}"

RUN wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip \
    && apt install unzip \
    && unzip ninja-linux.zip -d /usr/local/bin/ \
    && rm ninja-linux.zip
